# -*- coding: utf-8 -*-
"""module.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TleQbGQ3wWge1-3gz6W1EICA_T7yvMhN
"""

import numpy as np


def tukey_depth(X):
    depths = []
    for p in X:
        angles = np.arctan2(X[:, 1] - p[1], X[:, 0] - p[0])
        min_count = len(X)
        for angle in angles:
            u = np.array([np.cos(angle), np.sin(angle)])
            projection = X @ u
            p_projection = p @ u
            n1 = np.sum(projection <= p_projection)
            n2 = np.sum(projection >= p_projection)
            min_count = min(min_count, n1, n2)
        depths.append(min_count / len(X))
    return np.array(depths)
